### ISSUE TITLE
Ability to randomize which document is shown at what time

### ISSUE THREAD

**Issue by xehu** [StanfordHCI/bang#310]
Suppose, for example, that I have 2 documents, A and B. Sometimes, I might want the order to be ABAB, or I might want it to randomize and be BABA. 

I would want to show different docs in different rounds. The doc would be shown as part of a step.

The logic goes as follows.
I have a list of docs = [A, B, C, D].
This list of docs is scrambled at the beginning of each BATCH.

For example, suppose I scramble and I get [D, C, A, B].

Then, within a batch, each Task would use these docs in order. Task 1 will show document D; Task 2 will show C, Task 3 will show A, and Task 4 will show B. There will only be one doc per batch and it will be shown exactly once.

The same doc will be, ideally, accessible in the pre- and post-round surveys.

If there are N docs and K rounds, N docs would be randomized, and in each of the K rounds you would show the N%Kth document.

The most common use case will be 2 docs and 4 rounds.

**Comment by markwhiting** [comment]
Is this still needed with the current design?

**Comment by xehu** [comment]
Looks like cases and randomization are done. Closing this issue.
