### ISSUE TITLE
Update user chat display settings based on pre-survey

### ISSUE THREAD

**Issue by phoebexy** [StanfordHCI/bang#414]
Context:
We currently have the functionality to deliver a pre-survey to users prior to the start of all rounds.

Change:
Based on the user's pre-survey answers we want to modify the display of their chat presence across all rounds of the batch.

Specific modification:
Specifically, we'd like to make the user's avatar gendered based on the user’s answer to a gender pre-survey question.

**Comment by phoebexy** [comment]
@deliveryweb  looking at https://bang-dev.deliveryweb.ru/ I see the avatars checkbox in the batches page, but I don't see the pre-survey functionality in the template. The avatar genders are supposed to be chosen based on a gender question in the pre-survey of a template so I'm not sure how the functionality works. Could you please explain? Thanks!

**Comment by deliveryweb** [comment]
Hi! As previously mentioned, there is a specific question:

**Comment by phoebexy** [comment]
Gotcha thanks! that's clear. Now I think we just need to see the pre-survey in the template!
