### ISSUE TITLE
Morality: UI element that allows the jury to choose a foreperson.

### ISSUE THREAD

**Issue by xehu** [StanfordHCI/bang#425]
In my task, I would like the members of a chatroom to vote on someone to be the "foreperson," or the leader. **Therefore, I would like a UI element that enables voting to take place easily and naturally.**

List of all required features:
- In the template, there should be a toggle that turns "foreperson voting" on or off.
- In a chatroom, the first thing that helperBot says should be to ask to vote for one of the users in the room.
- The helperBot should present the user with 3 buttons that indicate whom to vote for.
- Once the user votes, helperBot should display the results of who the leader is.

SAMPLE of possible implementation vision:

<img width="697" alt="Screen Shot 2019-09-03 at 4 46 45 PM" src="https://user-images.githubusercontent.com/28793641/64216161-7ff40880-ce6c-11e9-81cb-b5bc5a5fcd44.png">
<img width="703" alt="Screen Shot 2019-09-03 at 4 47 00 PM" src="https://user-images.githubusercontent.com/28793641/64216162-7ff40880-ce6c-11e9-9a6b-170be4debe89.png">
<img width="700" alt="Screen Shot 2019-09-03 at 4 46 55 PM" src="https://user-images.githubusercontent.com/28793641/64216163-808c9f00-ce6c-11e9-8efc-e39b5b61d3a1.png">

**Comment by deliveryweb** [comment]
in dev
