### ISSUE TITLE
Ability to Collaboratively Answer a Survey

### ISSUE THREAD

**Issue by xehu** [StanfordHCI/bang#426]
In my task, I would like all the people in the same room to be able to answer a survey **collaboratively**. That is to say, everyone should be able to work together to answer the survey questions, and they have to agree on the answers before they submit.

This shared survey can be edited (opened and closed) multiple times, and users can return to the chatroom and continue talking in between editing the survey until the time in the room runs out.

List of all required features:
- The survey should be specified in the template.
- There should be some ability to open and close the shared survey. Once one person opens the survey, the survey will be opened by everyone.
- Any change made by any one user to the survey should also be reflected in what everyone else sees. That is, there is only 1 global version of the survey.
- Users can close the survey and return to the chatroom, then open it up again. This can occur repeatedly until the time in the chatroom runs out.
- The survey cannot be submitted until it is completely filled out and everyone is in agreement.
- When opening/closing the survey, the user sees a dialog box that explains how the survey works: namely, (1) that everyone may edit at the same time, but they must agree on the final answers. (2) that users may return to edit the survey multiple times until the end.

**SAMPLE of possible implementation vision:**

1. Button to open shared survey:
<img width="170" alt="Screen Shot 2019-09-03 at 5 26 52 PM" src="https://user-images.githubusercontent.com/28793641/64216954-0eb65480-ce70-11e9-8df4-8c9361f0b2b7.png">

2. SAMPLE of joint editing UI:
<img width="600" alt="Screen Shot 2019-09-03 at 4 54 03 PM" src="https://user-images.githubusercontent.com/28793641/64216094-47542f00-ce6c-11e9-91d8-cf94f9b87aa7.png">

**Comment by deliveryweb** [comment]
in dev
