### ISSUE TITLE
Add "null" as answer type to survey

### ISSUE THREAD

**Issue by phoebexy** [StanfordHCI/bang#432]
Currently, there are only two answer types: "Select" and "Text"

However, there are some surveys (such as in the status survey) where we'd like to provide instructions at the beginning of each group of questions. In this case, we need to create a question with the answer type "null" so that the user isn't required to respond to the question.

See image below
<img width="729" alt="Screen Shot 2019-09-17 at 5 15 36 PM" src="https://user-images.githubusercontent.com/24863065/65083708-dbdf8680-d96e-11e9-9972-2b84a15df441.png">

**Comment by deliveryweb** [comment]
done, in dev
