### ISSUE TITLE
Select multiple surveys to include in Batch Template

### ISSUE THREAD

**Issue by phoebexy** [StanfordHCI/bang#433]
Currently, we can choose to insert a single survey automatically as the pre-survey or mid-survey after each round in a batch template.

Now, we want to be able to automatically insert multiple surveys in the pre-survey or mid-survey section of each round in the batch template.

This could look like an "Add Survey" section in the Batch Template where you add and delete survey selections. The survey is not imported into the Batch Template, rather, the Template references the original Survey Object such that when the survey is updated, the batch template uses the updated survey object and needs no further updating.

**Comment by dtatarenkov** [comment]
@phoebexy

**Comment by phoebexy** [comment]
Sorry for the delay! Gotcha, then could we make it easier to construct single surveys using multiple surveys? For example, it would be great to have a JSON download survey button so I can easily concatenate and modify existing surveys.

**Comment by dtatarenkov** [comment]
in dev in "surveys" tab.
you can now download survey data and upload it after adding/deleting content
