### ISSUE TITLE
Information about users is hard to find in the UI

### ISSUE THREAD

**Issue by markwhiting** [StanfordHCI/bang#436]
# Problem
We often need to find a particular user and understand the experience they had on the platform. The most common thing we need is: 

1. to search by mturk ID, 
2. to check if they've been paid, and bonus them if they haven't. 

# Solution
I propose that we add a few changes to make this much easier. 

1. a search field which allows entering an mturk ID and just returns any records we have of that user on `https://bang.stanford.edu/users`
2. a payment column which shows how much we've paid that worker

A nice to have would be: 

3. A bonus button so we could just bonus that worker directly from the `users` ui.

**Comment by dtatarenkov** [comment]
added bonus button and total bonuses to users tab
