### ISSUE TITLE
[bug] user is sometimes kicked out randomly in the middle of a batch

### ISSUE THREAD

**Issue by xehu** [StanfordHCI/bang#439]
I was running a batch with the following settings:
1. Multi-team
2. Team size = 4
3. Using 16 dummy users (test urls from database)
4. bang dev

And at some point between round 1 and round 2, 12/16 of the users were "kicked out" and given the "we don't have a batch at this time" message. This seemed inexplicable; I was watching the 16 windows and making sure they were all active, and it seemed to occur without much warning.

**Comment by xehu** [comment]
Message received following getting kicked out:
<img width="986" alt="Screen Shot 2019-10-03 at 6 12 51 PM" src="https://user-images.githubusercontent.com/28793641/66252080-f30eca00-e70b-11e9-8115-1bdac56f4820.png">

**Comment by deliveryweb** [comment]
Hi! Current flow works like this: If user didn't type anything in round 1 he gets kicked in round 2. Was the flow different while you testing? @xehu

**Comment by xehu** [comment]
@deliveryweb that might be the reason why!

Can you possibly give a different error message, that says something along the lines of **"because you were inactive, you have been removed from the study"**? That might be helpful in distinguishing expected from unexpected behavior.

**Comment by deliveryweb** [comment]
ok

**Comment by markwhiting** [comment]
@xehu that could get us a lot of pushback from workers.

Perhaps: 
```This task requires workers to be active in every round to work. Because you were not active in the last round your session has been stopped.```

But I'm open to improvements on this. 

Also, I'm pretty sure we make that clear in earlier instructions, but just to double check. We need to make it really clear to them that being inactive will result in them being removed, before it happens, as well as explaining what happened when it does.

**Comment by deliveryweb** [comment]
After kick user is redirected to page with this text 

> `This task requires workers to be active in every round to work. Because you were not active in the last round your session has been stopped.`
