### ISSUE TITLE
[bug] after a survey, the timer is frozen and does not advance

### ISSUE THREAD

**Issue by xehu** [StanfordHCI/bang#440]
After completing a survey, some user screens were frozen at timer 0:00 with no ability to advance. This issue was also reported in prod by some users (via emails, that I recall).

Screenshot:
<img width="1106" alt="Screen Shot 2019-10-03 at 6 31 01 PM" src="https://user-images.githubusercontent.com/28793641/66252093-1afe2d80-e70c-11e9-9ce0-50f83192b055.png">

Parameters: 
1. Multi team
2. Team size = 4

**Comment by dtatarenkov** [comment]
should be working now
