### ISSUE TITLE
hide sidebar displaying other users during all reading periods.

### ISSUE THREAD

**Issue by xehu** [StanfordHCI/bang#443]
In the reading period, where **the user should be the ONLY person in the room, and left alone to read**, I noticed that, at one point, another user actually appeared: 

<img width="273" alt="Screen Shot 2019-10-03 at 6 15 41 PM" src="https://user-images.githubusercontent.com/28793641/66252155-cdce8b80-e70c-11e9-819f-b7fc2ad51887.png">

Settings used:
1. Multi team
2. Rounds = 4
3. Reading, pinned, all surveys = on

**Comment by markwhiting** [comment]
I'm not disputing this bug, but just wondering, why is reading period in a chatroom instead of on a page with a link, or something else? 

Is that what we want? Is there a way this could work better fundamentally?

**Comment by xehu** [comment]
@markwhiting you're right--- it doesn't have to be in a chatroom. The idea was to make the experience feel consistent with the rest of the platform.

I think alternative ways of doing this include just creating a blank page where the reading materials are embedded, with some timer counting down how much time they have left. The "minimum viable product" is just having some ability to display:
1. instructions
2. time limit (timer countdown)
3. a PDF (or a link)

**Comment by markwhiting** [comment]
Whats the ideal, from an experimental standpoint?

**Comment by xehu** [comment]
I don't think there's a huge experimental tradeoff either way, but ideally, the reading period is just a quiet time to read on one's own. It just doesn't make sense to me for it to appear like there's lots of other users "there," since you can't interact with them until the chatroom anyway.

@deliveryweb can you just hide the sidebar during all reading periods?

**Comment by xehu** [comment]
^changed title of the issue to make the action item more clear.

**Comment by dtatarenkov** [comment]
fixed
