### ISSUE TITLE
pre-survey gender logic not working on all rounds

### ISSUE THREAD

**Issue by phoebexy** [StanfordHCI/bang#447]
I'm testing the gendered avatars feature via the template here: https://bang-dev.deliveryweb.ru/templates/5da0fe2c9411f81829c7cba1

There is an error where the round immediately following the pre-survey does not display the gendered avatars, while avatars in consecutive rounds do.

My hypothesis is that gendered behavior is only activated for masked rounds. Instead, we would like the gendered avatars to appear in all rounds regardless of experimental condition in an applicable batch.

<img width="1055" alt="Screen Shot 2019-10-11 at 3 23 51 PM" src="https://user-images.githubusercontent.com/24863065/66688789-f2f75880-ec3c-11e9-9f6d-5a79d9d80867.png">
<img width="1090" alt="Screen Shot 2019-10-11 at 3 26 13 PM" src="https://user-images.githubusercontent.com/24863065/66688790-f2f75880-ec3c-11e9-8835-df415690da59.png">

**Comment by dtatarenkov** [comment]
done

**Comment by deliveryweb** [comment]
in prod

**Comment by phoebexy** [comment]
Hi @deliveryweb tested the dev version and found a major bug. 

see the test batch I ran here: https://bang-dev.deliveryweb.ru/batches/5dae1f6cfbc76e538e94b3b2

The first round task is delivered twice, once before the first round pre-survey and once after the pre-survey. the order should be: [pre-survey, first round, mid round], [repeat for other rounds] with no round repetition. The gender avatars also did not display in the second "first round" task

**Comment by phoebexy** [comment]
Additionally, I tested the same Status template without the pre-survey and it seems to be working fine, so I believe the bug originates in the pre-survey functionality.

**Comment by phoebexy** [comment]
Please test with the Status Template to check the solution works!

**Comment by phoebexy** [comment]
Here's a screenshot of what I see on the website after the pre-survey 
<img width="1081" alt="Screen Shot 2019-10-21 at 2 25 17 PM" src="https://user-images.githubusercontent.com/24863065/67247026-0eb8e680-f415-11e9-817b-09e428e976d0.png">

**Comment by dtatarenkov** [comment]
fixed, in prod
