### ISSUE TITLE
Final survey countdown doesn't kick users out

### ISSUE THREAD

**Issue by phoebexy** [StanfordHCI/bang#448]
<img width="1148" alt="Screen Shot 2019-10-12 at 4 04 25 PM" src="https://user-images.githubusercontent.com/24863065/66708728-1b995400-ed0a-11e9-8503-e4bc36526e3b.png">

The user has reached the final survey and the count down is at 0, however, the user has not been kicked out of the experiment.

**Comment by dtatarenkov** [comment]
behavior is expected
