### ISSUE TITLE
Experiment complete, final survey not kicking users out

### ISSUE THREAD

**Issue by phoebexy** [StanfordHCI/bang#449]
<img width="1148" alt="Screen Shot 2019-10-12 at 4 04 25 PM" src="https://user-images.githubusercontent.com/24863065/66783327-896d8900-ee8c-11e9-85c1-6ad3da7036b6.png">

At the final survey of the batch, the timer reaches 0 but users are not kicked out. Is this the expected behavior?

**Comment by dtatarenkov** [comment]
This behavior is expected, we can change it if there is a need @phoebexy
