### ISSUE TITLE
Polls are not working + Functionality Issues with Polls

### ISSUE THREAD

**Issue by xehu** [StanfordHCI/bang#451]
This Issue describes 3 separate problems:
1. **Polls, as specified, do not appear at any point in the round.**
2. **There is only the ability to specify one poll**, but there should be the ability to have more than one poll.
3. **There is no ability to specify when a poll appears in the round.** Ideally, the Foreperson poll should appear at the very beginning (and then disappear); the "final vote" poll should appear at the very end of the round, when the team members submit their final decision.

-----
Currently, in the template, I checked the box to create a poll:
<img width="168" alt="Screen Shot 2019-10-28 at 3 10 17 PM" src="https://user-images.githubusercontent.com/28793641/67722783-56042180-f997-11e9-9280-782bdcaffcb7.png">

This resulted in the following option:
<img width="680" alt="Screen Shot 2019-10-28 at 3 10 09 PM" src="https://user-images.githubusercontent.com/28793641/67722794-5dc3c600-f997-11e9-8bc3-403d9601b854.png">

However, no such poll ever appeared in the final result.
This poll-creating form should also have the ability to specify:
(1) the time that the poll will appear (using the same time-slices as the steps, since a poll could be part of the steps); and 
(2) the ability to add more than one poll.

**Comment by dtatarenkov** [comment]
fixed functionality, if polls don't work in dev, join the batch with willbang users
