### ISSUE TITLE
Random 'hung jury' messages appear

### ISSUE THREAD

**Issue by xehu** [StanfordHCI/bang#452]
Even though the polls never appeared, **I got ‘hung’ jury messages at really random points throughout the flow**:

<img width="1280" alt="bug - hung jury again" src="https://user-images.githubusercontent.com/28793641/67722982-dfb3ef00-f997-11e9-81d4-516845dba866.png">
<img width="1280" alt="bug - more random hung jury" src="https://user-images.githubusercontent.com/28793641/67722986-e2aedf80-f997-11e9-9eee-b27e5d746b4c.png">
<img width="344" alt="2 bugs - polls never appeared, and 'hung jury' appeared even though there was no poll; also appeared very late" src="https://user-images.githubusercontent.com/28793641/67722994-e6dafd00-f997-11e9-8587-10e9b1cc97c2.png">

**Moreover, the 'hung jury' message itself was cut off.** The format for this may not be ideal for a small pop-up; perhaps consider briefly redirecting the user to a page that says "hung jury!" instead.

My questions to this end are:
1. What is the underlying data structure being checked, to determine when these "hung jury" messages are being sent out?
2. How is that data structure populated?
3. If there is a hung jury, can we communicate the hung jury in a more clear way, instead of just a small corner pop-up?

**Comment by deliveryweb** [comment]
The timings will be fixed.

I don't really have any ideas about a more clear way of communication since we don't really have any other tools @xehu

**Comment by deliveryweb** [comment]
The 'hung jury' messages now appear if the poll has foreperson type and is not completed (teamSize - 1 votes are on the same person):
1. 5 minutes before round end
2. 2.5 minutes before round end
3. 10 seconds before round end
@xehu

**Comment by xehu** [comment]
Hey, looks like we have a bit of a misunderstanding on what a 'hung jury' is. This is my fault - I didn't explain how polls work 100% clearly.

So, there are 2 kinds of polls: 

1. **Foreperson polls** are meant to determine who the leader is. Foreperson polls are _not by consensus. Whoever gets the most votes wins._ There should _never_ be a hung jury as a result of a foreperson poll.

2. The second type of poll **determines the result of the deliberation**. Here, there should be the _option_ to force everyone to agree. In fact, more generally, there should be the ability to set a threshold of what percent of people need to vote for an option in order for the poll to pass. (The default for the result-type poll should be changeable. For now, let's set the default at 100%---but again, there should be the option to set a custom threshold.) _If that threshold is set at a certain percentage_, and we do not meet that percentage, then we get a hung jury.

Does this clear up what a hung jury means?

**Comment by deliveryweb** [comment]
@xehu right now we have a foreperson poll and a casual poll where we can set the answer options. Do I understand you correctly, you want to move the hung jury notifications from the foreperson poll to the casual one?

**Comment by xehu** [comment]
@deliveryweb yes. The hung jury notifications should be moved from foreperson to causal!

**Comment by xehu** [comment]
I put this information in the Slack channel, but always good to document it here as well! Here is, just for reference, a more detailed description of the two polls:

In a **foreperson** poll, the goal is to choose the leader of the team.
- When selected, the foreperson poll should enable the user to type the text of the question.
- There does not need to be a specification of the poll’s options, because by default, the options should be the list of the names of the team members (littleHorse, spunkyHippo, etc.)
- The person who gets the most votes becomes the foreperson. This should get displayed on the screen next to their name.
- If there is a tie, no one is the foreperson. There should not be a hung jury.

In a verdict, or result poll, the goal is to decide the result of the discussion. Generally, this will be used in a case where the group is meant to decide some outcome.

- When selected, the result poll should first enable the user to set a decision threshold.
- The threshold should be a number between 0.5 and 1.
- If there are n people on a team and the threshold is k, then there must be at least n*k votes for one particular option in order for the poll to be decided.
- For example, if the threshold is 0.5 and there are 6 members on the team, then there must be at least 3 people in favor of a single option in order for a vote to be decided.
- If the threshold is 1, it means everyone must be in agreement.
- While the threshold is not met, the poll should indicate that we have not yet met the threshold (for example, by saying “need to reach 50%”).
- When the threshold is never met and time runs out, there is a hung jury.

Each poll can have multiple questions. Questions can either be of multiple choice or text input. 
For now, the decision threshold should only be applied to multiple choice questions. In the future, we should come up with a way for people to agree on text input options.

**Comment by dtatarenkov** [comment]
fixed, in dev
