### ISSUE TITLE
Some messages that were sent ended up empty

### ISSUE THREAD

**Issue by xehu** [StanfordHCI/bang#453]
In some rounds, when a user typed a non-empty message, it would appear as empty in the chat (to themselves and to others). This was a bug that had also been reported by some Turkers when we were running real trials.

View from the user:
<img width="1126" alt="bug - texts appear empty" src="https://user-images.githubusercontent.com/28793641/67723158-6963bc80-f998-11e9-936a-04560c2efefe.png">

View from other users:
<img width="273" alt="bug - empty messages (as shown to others)" src="https://user-images.githubusercontent.com/28793641/67723165-6ec10700-f998-11e9-8368-d41fe7ed22ee.png">

**Comment by deliveryweb** [comment]
@xehu this was fixed in prod and happens only in dev when a user was AFK and kicked. After refreshing the page everything should work as expected (the user should be kicked)

**Comment by deliveryweb** [comment]
This happens only in dev after a user was kicked for AFKing running in incognito mode. The issue was fixed in prod.

**Comment by xehu** [comment]
Okay - I'll keep an eye out for this issue again. However, I'm concerned that this is happening to people who are AFK without warning. It feels like the system is basically changing its state silently, and it can be very confusing for users who didn't know that they were kicked, and yet experience this issue anyway.
