### ISSUE TITLE
In some reading periods, the person's own name is missing.

### ISSUE THREAD

**Issue by xehu** [StanfordHCI/bang#454]
Ideally, in the reading period, **the user themselves should be the only person in the room.** Currently, it instead shows all users -- but it also has a bug, where the user themself is missing: 

<img width="1280" alt="bug - self is missing from reading period" src="https://user-images.githubusercontent.com/28793641/67723319-d9724280-f998-11e9-8ead-fcd7ecebcb52.png">

Ideally, we only need **one person** to appear in the users list in the reading room: **just the user's own name**.

**Comment by xehu** [comment]
For context, this occurred only in some reading periods, and this was a correct earlier version that showed everyone in the reading period who needed to be there:

<img width="1280" alt="success - reading period" src="https://user-images.githubusercontent.com/28793641/67723364-0b83a480-f999-11e9-809b-e98305fb2484.png">

**Comment by deliveryweb** [comment]
This only happens when the person was kicked due to the inactivity. In prod he is redirected to the kicked screen at that point, this logic just cannot be implemented in dev, so this flow is expected
