### ISSUE TITLE
Add demographics survey to pre-task and store in database to effect batch functionality

### ISSUE THREAD

**Issue by phoebexy** [StanfordHCI/bang#457]
We want to add the demographics survey in the pre-task MTurkers take before they take our main bang task.

We want to save the worker's information in the database and be able to access this data on the user to change batch functionality. The specific use case is: extending the gender avatar functionality into a setting that, when activated, pulls the worker’s gender from the db.

The demographics survey is below:
 
# Demographic Survey 
Description: Your answers to these questions will not effect your eligibility for future HITs.

What is the highest degree or level of school you have completed?
Less than High School
High school or equivalent
Some college
Undergraduate degree
Graduate degree
Doctorate

What is your gender?
Male
Female
Other

Which year were you born?
TEXT INPUT

How much total combined money did all members of your household earn last year?
Less than $20,000
$20,000 to $34,999
$35,000 to $49,999
$50,000 to $74,999
$75,000 to $99,999
Over $100,000

Are you of Hispanic, Latino, or of Spanish origin?
Yes
No

How would you describe yourself?
American Indian or Alaska Native
Asian
Black or African American
Native Hawaiian or Other Pacific Islander
White
Other

What is your marital status?
Single
Married
Live with Partner
Separated
Divorced
Widowed

What is your occupation? If you are retired, please describe your main occupation when you were working.
TEXT INPUT

How long have you worked in this occupation? (If you are retired, how long did you work in this occupation?)
TEXT INPUT

Have you ever served on a jury before?
Yes
No

If yes, how many times?
TEXT INPUT

Was it a civil or criminal case?
Civil
Criminal

Did the jur(ies) reach a verdict?
Yes
No

Would you say religion provides no guidance in your day-to-day living, some guidance, quite a bit of guidance, or a great deal of guidance in your day-to-day life?
No guidance
Some guidance
Quite a bit of guidance
A great deal of guidance

We hear a lot of talk these days about liberals and conservatives. Here is a seven-point scale on which the political views that people might hold are arranged from extremely liberal to extremely conservative. Where would you place YOURSELF on this scale?
Extremely Liberal
Liberal
Slightly Liberal
Moderate; Middle of the Road
Slightly Conservative
Conservative
Extremely Conservative

**Comment by xehu** [comment]
Questions to add: Political / Religious affiliation questions

Would you say religion provides no guidance in your day-to-day living, some guidance, quite a bit of guidance, or a great deal of guidance in your day-to-day life?
No guidance
Some guidance
Quite a bit of guidance
A great deal of guidance

We hear a lot of talk these days about liberals and conservatives. Here is a seven-point scale on which the political views that people might hold are arranged from extremely liberal to extremely conservative. Where would you place YOURSELF on this scale?
Extremely Liberal
Liberal
Slightly Liberal
Moderate; Middle of the Road
Slightly Conservative
Conservative
Extremely Conservative

**Comment by xehu** [comment]
@phoebexy not sure whether you think these questions are helpful: the paper I was basing my questions off of asked these to verify political affiliation

We would like you to tell us whether you would like to see spending increased or decreased on aid to the poor.
Increased
Decreased
About the Same

Read this statement, and tell us how strongly you agree or disagree.

‘Irish, Italians, Jewish and many other minorities overcame prejudice and worked their way up. Blacks should do the same without any special favors.’
[7-point Likert]

Read this statement, and tell us how strongly you agree or disagree.

‘Generations of slavery and discrimination have created conditions that make it difficult for blacks to work their way out of the lower class.’
[7-point Likert]

Read this statement, and tell us how strongly you agree or disagree.

‘Our society should do whatever is necessary to make sure that everyone has an equal opportunity to succeed.’
[7- point Likert]

Read this statement, and tell us how strongly you agree or disagree.

‘We have gone too far in pushing equal rights in this country.’
[7 - point Likert]

**Comment by dtatarenkov** [comment]
I will hardcode the questions and add the fields to database, should take 2-3 days to test everything @xehu @phoebexy

**Comment by xehu** [comment]
Great! @dtatarenkov can we get an update on this in our call tomorrow?

**Comment by phoebexy** [comment]
@xehu these questions look good. I've also added an intro description.

**Comment by xehu** [comment]
Yup, I'm happy with the survey as it currently stands.

**Comment by dtatarenkov** [comment]
in dev
IMPORTANT: questions should be asked in batch pre-survey, not in round survey.

**Comment by markwhiting** [comment]
@dtatarenkov  Can the following question be added to this before being pushed.

> **By submitting this HIT you agree to the following consent form.**
>
> **About the research**
> We are researchers at the Stanford HCI Group conducting research on team operations. As part of the research, you’ll join as a participant and perform individual and group tasks on several occasions. The task will take less than 2 hours of your time in total.
> 
> **Description**
> You are invited to participate in a research study that investigates team operations. As part of the research, you’ll join as a participant and perform a individual and group tasks on several occasions.
> 
> **Time**
> We expect less than three hours of your time.
> 
> **Risk and benefits**
>We anticipate no significant risks and no discomfort while you're participating in this program. If you find any part of the research uncomfortable or risky, you’re free to pause or stop participating. You’ll be compensated for the time and work you contributed. We cannot and do not guarantee or promise that you will receive any benefits from this study.
>
> **Payments**
> Participants will be paid through their online crowdsourcing marketplace according to the best practices laid out in the [Dynamo Guidelines for Academic Requesters](http://guide-lines.wearedynamo.org/).
>
> **Participant’s rights**
> If you have read this form and have decided to participate in this project, please understand your participation is voluntary and you have the right to withdraw your consent or discontinue participation at any time without penalty or loss of benefits to which you are otherwise entitled. The alternative is not to participate. You have the right to refuse to answer particular questions. The results of this research study may be presented at scientific or professional meetings or published in scientific journals. Your individual privacy will be maintained in all published and written data resulting from the study.
>
>**Contact information**
>If you have any questions, concerns or complaints about this research, its procedures, risks and benefits, contact the Protocol Director, Mark Whiting, mwhiting@cs.stanford.edu, (352) 226-9212. If you are not satisfied with how this study is being conducted, or if you have any concerns, complaints, or general questions about the research or your rights as a participant, please contact the Stanford Institutional Review Board (IRB) to speak to someone independent of the research team at (650)-723-2480 or toll free at 1-866-680-2906, or email at IRB2-Manager@lists.stanford.edu. You can also write to the Stanford IRB, Stanford University, 3000 El Camino Real, Five Palo Alto Square, 4th Floor, Palo Alto, CA 94306.

**Comment by danonya666** [comment]
@markwhiting which label exactly should be changed?

**Comment by dtatarenkov** [comment]
@markwhiting which label exactly should be changed?

**Comment by markwhiting** [comment]
Not sure I understand. My comment just meant to say we need to add that text into this recruiting hit. The entire block of text that I shared.

**Comment by dtatarenkov** [comment]
in dev
