### ISSUE TITLE
Helperbot's messages are hard to read (initial chatroom)

### ISSUE THREAD

**Issue by xehu** [StanfordHCI/bang#458]
While testing the system, I noticed that, in the initial chatroom, Helperbot says some important information (for example, about why they're waiting and how often they need to check in, in order to be counted as present and active). However, the scrolling nature of the chat means that **most of these messages are off-screen**, so it's very difficult to actually read these:

<img width="1063" alt="Screen Shot 2019-11-09 at 3 25 44 PM" src="https://user-images.githubusercontent.com/28793641/68617312-da68a100-047b-11ea-9d34-5fa28843053a.png">

I suggest putting the most important of these messages at the _top of the screen_, for example, underneath "we are waiting for n more MTurk users", or otherwise making these messages more permanent.

**Comment by xehu** [comment]
@markwhiting and @phoebexy  - adding you to talk about the best UI solution to this!

**Comment by dtatarenkov** [comment]
in dev
