### ISSUE TITLE
Important Usability Issues for Polls + Timing for Polls

### ISSUE THREAD

**Issue by xehu** [StanfordHCI/bang#459]
Polls currently work, but the UI is not very good because *they do not give the users great instructions on what they are for and how they are supposed to be used*.

I have created a new design flow for polls. *Instead of putting them in the side panel, please put the polls in a visually appealing top panel, similar to the pinned content.*

You can interact with this design here: https://www.figma.com/proto/kzKheEIoln04z1CcxpdZIf/Scaled-Humanity-Poll?node-id=0%3A1&scaling=min-zoom

Key changes:
1. Polls should appear *in tandem with specific steps.* So, for example, if step 1 is "choose a foreperson," the foreperson should appear at the same time as the step.
After the step is over (when the next step appears), the poll should disappear.
2. *The location of the poll should be at the top of the screen.*

Key screenshots:
![1 - Foreperson Poll](https://user-images.githubusercontent.com/28793641/69105466-2d17ff00-0a20-11ea-81f2-f8b9b1e68f14.png)
![2  - Foreperson Poll Post Voting](https://user-images.githubusercontent.com/28793641/69105467-2e492c00-0a20-11ea-88e4-717bea968a67.png)
![3 - Verdict Poll-2](https://user-images.githubusercontent.com/28793641/69105477-3903c100-0a20-11ea-84ec-305717ff431b.png)
![4 - Verdict Voting](https://user-images.githubusercontent.com/28793641/69105481-3b661b00-0a20-11ea-9243-9b418bb4be88.png)
![4 - Verdict Voting-2](https://user-images.githubusercontent.com/28793641/69105482-3dc87500-0a20-11ea-91a1-b1b5f6bb84f1.png)

**Comment by xehu** [comment]
Per the call: *One additional feature to add is that, once everyone has already filled out the poll and have reached agreement, you can remove the buttons for voting.* We would just want to display the results of the poll instead. It would look something like this:

![2  - Foreperson Poll Post Voting, buttons hidden](https://user-images.githubusercontent.com/28793641/69182745-7c186f80-0ac6-11ea-8239-80412d1689f9.png)

**Comment by xehu** [comment]
Deadline that we agreed on in the meeting: **11/21 or 11/22**.

**Comment by dtatarenkov** [comment]
in dev
