### ISSUE TITLE
Create More Complex Polls

### ISSUE THREAD

**Issue by xehu** [StanfordHCI/bang#460]
**[Removed 1-5 because they are resolved]**

6. **Add the ability to have multiple questions.** Currently, one poll can only have one question. It would be great to ask multiple questions per poll (just like a survey).

7. **Add the ability to have different answer types.** I'd like support for multiple choice and short answer.

8. **If a poll has multiple questions, add the ability to expand and collapse the poll.** That way, people can go back to viewing the discussion.

This feature update would look something like this: If you click on the "-" sign on the left, you would get the screen at the right. If you clicked on the "+" sign on the right, you would get the screen on the left.

<img width="684" alt="Screen Shot 2019-11-27 at 12 53 01 AM" src="https://user-images.githubusercontent.com/28793641/69708350-508e1a00-10b0-11ea-95a3-c9b846a41869.png">

**Comment by dtatarenkov** [comment]
Hi, I understand the importance of these updates, however there are some limitations because of the current structure. Here are some comments and possible solutions:
1. We cannot time poll appearance independently from the steps appearance. There must be a some kind of dependency between steps and polls. I made polls appear at the same time with the steps. We can change it to something else, but it has to be 'linked' with the steps somehow
2. fixed
3. fixed
4. fixed
5. fixed

**Comment by xehu** [comment]
With (1), I think your comment should work in theory---my observation is that it just doesn't seem to be working in practice. For example, I have two steps, one at 0.5 and one at 0.9, and a round of 5 minutes. When I pair the second poll with the second step, it does not appear at 0.9; instead it appears immediately after the first poll, and the step appears later.

**Comment by dtatarenkov** [comment]
yeah, it worked a little bit different, now it should be fine

**Comment by xehu** [comment]
let me test again and let you know!

Are (6)-(8) doable in the near future?

**Comment by dtatarenkov** [comment]
will be done after demographics survey

**Comment by dtatarenkov** [comment]
hi, there is a little question about threshold and this new functionality, if there are multiple select questions, how the threshold mechanic should work? @xehu

**Comment by deliveryweb** [comment]
Hello! As for the implementation of the surveys, we would offer the following implementation:
There will be two types of polls. Foreperson and casual.
For casual surveys, it will be possible to add a few questions. In the chat itself, the survey will be implemented as a form. For single answers, we will use radio buttons. For questions with a short answer, we will use a text box. 
For multiple-choice questions, we could use checkboxes. It would be a "send" button at the bottom of the form to be able to send the survey.  
In this case, the percentage would not be calculated for the casual polls at all.
@xehu @markwhiting  how do you feel about it?

**Comment by dtatarenkov** [comment]
in prod
