### ISSUE TITLE
Individual v. Team UI Issue

### ISSUE THREAD

**Issue by xehu** [StanfordHCI/bang#461]
This relates to how polls interact with the dynamic team size. **If we have a team size = 1, don't show the foreperson poll if it's set.** It doesn't make sense to vote for a leader if you're alone, and the poll is just empty:

<img width="1065" alt="Screen Shot 2019-11-27 at 12 58 38 AM" src="https://user-images.githubusercontent.com/28793641/69708936-53d5d580-10b1-11ea-9b26-e513c024796b.png">

**Comment by danonya666** [comment]
in dev

**Comment by dtatarenkov** [comment]
in dev
