### ISSUE TITLE
Reading Periods need to support .md and be much taller

### ISSUE THREAD

**Issue by xehu** [StanfordHCI/bang#462]
The current reading period experience is very poor when we have long text, and does not support .md. As you can see, a longer file only takes up about a third of the screen, and the visual experience doesn't include the formatting from the .md file: 
<img width="904" alt="Screen Shot 2019-11-27 at 2 22 27 PM" src="https://user-images.githubusercontent.com/28793641/69763309-a353ea00-1121-11ea-95fb-ddf4ee765841.png">

**Comment by dtatarenkov** [comment]
in dev
