### ISSUE TITLE
Some reading periods are completely blank

### ISSUE THREAD

**Issue by xehu** [StanfordHCI/bang#463]
**Urgent:** I found a bug where it seems like a few users' reading periods are completely blank. This issue seems to exist for one round---that is, for the same user, multiple reading periods in the same round are empty (see screenshots). However, reading periods in subsequent rounds are unaffected.
<img width="901" alt="Screen Shot 2019-11-27 at 6 50 49 PM" src="https://user-images.githubusercontent.com/28793641/69773670-4ddf0380-1148-11ea-82ea-dbb4938bde21.png">
<img width="912" alt="Screen Shot 2019-11-27 at 6 50 19 PM" src="https://user-images.githubusercontent.com/28793641/69773671-4ddf0380-1148-11ea-8549-c271af1afcb7.png">

**Comment by dtatarenkov** [comment]
seems to be fixed, could you tell me more about what was your sequence of actions before this bug appeared? @xehu

**Comment by xehu** [comment]
I tested a few more times and have not encountered the bug again.

I used the morality-test template on bang-dev, used all default settings, single-team masked, and opened 6 windows on incognito mode using the first 6 users in the database.

**Comment by xehu** [comment]
after further testing, I haven't seen the bug and am closing this issue
