### ISSUE TITLE
In Round 2, the Verdict Poll appears before the Foreperson Poll

### ISSUE THREAD

**Issue by xehu** [StanfordHCI/bang#464]
I have discovered a bug where, in Round 2, the verdict poll briefly appears at the beginning of the round, **before the foreperson poll appears**. It seems like, in the brief gap between the start of the round and the start of the first step, the previous verdict poll is still showing up and is not getting cleared out.

Screenshots below!

At the beginning of the round, we see this:
<img width="1280" alt="Screen Shot 2019-11-28 at 4 21 00 PM" src="https://user-images.githubusercontent.com/28793641/69836115-73791500-11fb-11ea-916c-c1e1f90286e5.png">

Then, a few seconds later, timed with the first step, the foreperson poll (the correct poll) appears:
<img width="1280" alt="Screen Shot 2019-11-28 at 4 21 05 PM" src="https://user-images.githubusercontent.com/28793641/69836129-82f85e00-11fb-11ea-8d66-4812f5acba1c.png">

**Comment by dtatarenkov** [comment]
Changed the poll timings, a poll appears in the same with step message, so if on the template page we chose that poll appears on the step 0 (step 1 in chat) the poll will appear on that step simultaneously with the message. If we have a poll appearing on step 1 (step 2 in chat) we will be seeing the second poll when the second message appears. Is it okay? Closing issue for now
