### ISSUE TITLE
[BUG] Reading Periods are Not Working

### ISSUE THREAD

**Issue by xehu** [StanfordHCI/bang#465]
Reading periods are not working. Some reading periods appear blank, while others are working fine. Critically, when Reading Period 1 is blank but Reading Period 2 contains the jury instructions, people complain that it is “backwards.”

Quotes from Turkers:
"The page went down so I'm reading the case quickly now"
"hmm didn't get the case again"
"The waiting period before is a blank page. So we are missing a step it seems."

**Comment by dtatarenkov** [comment]
fixed, should be working now
