### ISSUE TITLE
[BUG] Numerous reports of the page going blank after the reading period.

### ISSUE THREAD

**Issue by xehu** [StanfordHCI/bang#466]
Telling people to refresh sometimes fixes the issue, but not always. People generally freak out with blank pages, and some people leave---which is a big problem.

Quotes:
"The page went blank for me when the timer ran out for reading instructions."
"There were six of us and after the jury instructions, the screen just went blank."
"I don't know what happened. I was in the study and did the 2nd part reading and then everything went blank."

Refreshing does not work:
"I tried to refresh and nothing happened. The page was just blank."

**Comment by dtatarenkov** [comment]
should work now
