### ISSUE TITLE
Filter new batch invite by demographics pre-task response

### ISSUE THREAD

**Issue by phoebexy** [StanfordHCI/bang#468]
We want to be able to filter email invites sent out to users with each new batch by the pre-task demographics data we collected.

Add a "filter by" section in https://bang-dev.deliveryweb.ru/batches-add 

Allow the researcher to add filters with specific variables that match the demographic pre-task responses: age (age range), gender (male, female, other), ethnicity (see survey response), family salary (see survey response)

Emily / Mark would you recommend implementing any other filters?

**Comment by markwhiting** [comment]
I think thats a good starting point. I think once we have the data we can refine our filters moving forward.

**Comment by dtatarenkov** [comment]
added filter options to add-batch page
