### ISSUE TITLE
Polls between rounds show up twice if not filled out

### ISSUE THREAD

**Issue by xehu** [StanfordHCI/bang#469]
**If the verdict poll is not filled out in a previous round, it shows up again at the beginning of the subsequent round.** Sets of polls between rounds should be independent, so the polls should be cleared and should behave the same regardless of what the user did in the last round.

**Comment by xehu** [comment]
Actually, just realized (1) of this issue is the same as #461

**Comment by dtatarenkov** [comment]
fixed
