### ISSUE TITLE
Enable Users to Set Times for Displaying Cases

### ISSUE THREAD

**Issue by xehu** [StanfordHCI/bang#471]
Currently, if you have cases, you are required to also have reading periods as well, because there is no way to specify now long a case should be displayed for. **This is inefficient---the purpose of having cases is to prevent the experimenter from having many unnecessary, manually-created reading periods.**

I suggest a way to specify how long each part of the case should be displayed for, so that the cases can effectively be standalone reading periods (without having to define additional reading periods).

Such a feature would look something like this:
<img width="984" alt="Cases-Updated-With-Time" src="https://user-images.githubusercontent.com/28793641/72061105-0f318280-328a-11ea-8013-dfee5126881a.png">

The users would be able to say, for example, that they want "Case 1 Version 1" to display for 10 minutes in a reading period, and "Case 2 Version 2" to display for 3 minutes.

**Comment by dtatarenkov** [comment]
in prod
