### ISSUE TITLE
Status Experiment: 3 round individual teams functionality

### ISSUE THREAD

**Issue by phoebexy** [StanfordHCI/bang#473]
Your friendly neighborhood Stanford student researcher would like to run experiments with 4 people teams (single) that only have 2 or 3 rounds. Right now, the template displays INVALID when the researcher attempts to create a batch with only 2 or 3 rounds. Please help her implement this functionality so that she can run experiments with only 2 or 3 rounds for single teams AS WELL AS select on the template:

1. If she wants to mask the rounds (every round displays different aliases for the 4 team members) or unmask a round (every round displays the same aliases for the 4 team members)

**Comment by phoebexy** [comment]
The details for point 1 are still dependent on discussions surrounding the status experimental design with @markwhiting

**Comment by markwhiting** [comment]
@phoebexy do we still need this or did we decide on a longer design?

**Comment by phoebexy** [comment]
Closing this issue!
