### ISSUE TITLE
Its hard to find a specific user

### ISSUE THREAD

**Issue by markwhiting** [StanfordHCI/bang#477]
If we are searching for a user on the platform, it can take clicking through many pages. 

2 options seem useful alternatives to this: 

1. Provide a user ID field with which we can do a search for an mturk ID — this only needs to be a string match, not a real search, but it should be able to deal with things capitalization changes on letters in the string.
2. Render the entire table on one page — I think modern browsers should be able to handle this even if the number of rows is reasonably large. 

Which options seems better, and how long would each take to implement?

**Comment by dtatarenkov** [comment]
I think the first option is easier, I think it can be implemented quite fast, around a day. Should we do it after #473 #474 and #336? @markwhiting

**Comment by markwhiting** [comment]
Sure, do it when those other ones are resolved.

**Comment by dtatarenkov** [comment]
in dev
