### ISSUE TITLE
Bonusing a user requires using off platform techniques

### ISSUE THREAD

**Issue by markwhiting** [StanfordHCI/bang#478]
We sometimes need to send an extra bonus to a user due to a failed experiment or something else. Right now doing this requires sending the bonus off of the platform, e.g., by using some legacy code we have, or by using the MTurk UI, which is very cumbersome. 

I propose a solution that adds a bonus function to the users page. The following would be required: 

1. A new column on the users page that tells us how much a user has been paid in total so far from our records in the DB.
2. A new button that says "Bonus". It should appear near the bonus column and should occur once for each user. 
3. A modal window that comes up when the button is pressed and requires an number amount of dollars and an optional simple string message. It can then have a way of confirming and a way of canceling. e.g., "Send bonus", "Cancel" buttons.

When the button is pressed the modal should appear. If it gets an amount it should be enabled to send a bonus. When pressed a bonus should be sent to the corresponding user.

What do you think? Are there any hidden issues that should be considered? How long do you think it would take to implement this?

**Comment by dtatarenkov** [comment]
added bonus buttons to users tab
