### ISSUE TITLE
Timer goes down to 0:00, does not advance to next round

### ISSUE THREAD

**Issue by xehu** [StanfordHCI/bang#480]
Multiple individuals have reported this bug:

> Was doing the hit and finished round 2 (story and chat) and the countdown reached 0:00 and stayed there. I refreshed the page and only see this now "Thank you for your work. We will pay you shortly for your work based on $12/hour pay rate.

> I made it through 2 rounds of am I an asshole and then if froze and wouldn't allow me to move forward.  We had been instructed earlier to refresh the page if that happened and when I did it seemed to kick me out.  :(
 
> HI I was in your survey and at the end of round 3 the page just went down to 000 and never went forward.

> I made it all the way through round 3 on this task before it crashed on me. The timer counted down to 0, but round 4 never started. Will I be compensated for this task?

> ALOT of technical difficulties. The Bang page had to be self reloaded I don't know how many times. A lot of blank pages . I only succeeded in completing it through the Gmail opened browser. Then it told me repeatedly I was on round 2.

-----
**Technical Description of Bug**
- Typically, after round 2 or round 3, the reading period preceding round 3 or round 4 freezes.
- The timer for the reading period decrements to 0:00, and the remainder of the page becomes blank.
- The experiment does not advance to the next round.

Screenshot sent by a live user on Prod:
<img width="960" alt="2020-02-05" src="https://user-images.githubusercontent.com/28793641/73890597-334f9780-4827-11ea-86eb-6234e176593b.png">

**Batches that experienced this issue**
**In Dev**: https://bang-dev.deliveryweb.ru/batches/5e3a788125def02cc80558dc
Used the template `morality-test`,  with all default settings except `Dynamic` team size.

**In Prod**: https://bang.stanford.edu/batches/5e3ae919c73b496680fad6e8
https://bang.stanford.edu/batches/5e3aec27c73b496680fad9b5

Used the template `Morality Reddit1`, with default settings except `Dynamic` team size.

**Comment by xehu** [comment]
UPDATE: looks like this issue can be duplicated whenever you run a batch with the **Dynamic Team Size** setting on. We think we found a cause.

**Comment by dtatarenkov** [comment]
@xehu, the bug is located. The problem with it is the single-team features, which require to reconvene the chat of the 'best' and 'worst' rounds in the last/one-before-last rounds (#410 ). I fixed it in dev, now it works like that: if original round and reconvening round have different team sizes, we just do not display the old messages. Instead the chat is just empty as usual. Should it work like that, or there have to be changes? if it's ok, I can push to prod

**Comment by xehu** [comment]
@dtatarenkov: Thank you for locating the bug! I actually think your solution is great -- in fact, it brought to my attention things about the system that I did not understand before. My experiment requires that we don't reconvene any rounds, so it's great that you're creating an empty chat instead.

In fact, I would like to make it possible to make all of the chats start out empty, and not 'reconvene' any of them. The related issue is #484.

**Comment by dtatarenkov** [comment]
in dev together with #484
