### ISSUE TITLE
duplicate round task error [HIGH-PRIORITY]

### ISSUE THREAD

**Issue by phoebexy** [StanfordHCI/bang#481]
There is an error with task delivery in the Status 4 round, within teams, masked experiment! See here for the logs of the Round 3 and Round 4 task duplication.

https://bang-dev.deliveryweb.ru/batches/5e3a7d5f25def02cc8055c37

The round 4 task appears in both Rounds 3 and 4. Each round should have a unique task delivered by the chatbot.

This is a BAD blocking bug, please prioritize as high as possible!

**Comment by dtatarenkov** [comment]
hi, @phoebexy, this works like that because of the #428 issue, how should we change the flow?

**Comment by phoebexy** [comment]
I am not using the "reconvening" functionality that was requested in that issue. The default order should still be simple randomized rounds and we should not be seeing duplicates. Please make this flow a setting rather than the default!

**Comment by phoebexy** [comment]
@dtatarenkov we are using these default settings in our batches. If we do not want to reconvene functionality in our status experiments, how should we set these settings?

<img width="721" alt="Screen Shot 2020-02-06 at 1 48 37 PM" src="https://user-images.githubusercontent.com/24863065/73981702-a28cc080-48e7-11ea-855b-ef6ae98bb875.png">

**Comment by dtatarenkov** [comment]
you can just set the 'randomize' option to "don't randomize" and everything should be okay @phoebexy

**Comment by dtatarenkov** [comment]
i can make it default if you want

**Comment by phoebexy** [comment]
Yes, thank you! Does the "highest score" functionality affect the delivery if "Reconvene Worst"  and "Randomize last 2" are set to "Don't"? @dtatarenkov

**Comment by dtatarenkov** [comment]
it determines the function to calculate the best round, the messages from that round are added to the last round from the start of it

**Comment by dtatarenkov** [comment]
it is possible if the worst team will be reconvened too, then the best team reconvening round will have the last task and the worst will have second-from-last task. If worst is not being reconvened and last 2 rounds are randomized, there is a possibility of task duplicating. I can fix it and make the non-reconvening round always get the unused task. Is it OK @phoebexy ?

**Comment by phoebexy** [comment]
Hmm, I'm not familiar with the exact details of the reconvening functionality. But as long as you can help us hit the goal of having 4 tasks delivered in a random fashion with no duplicates + one reconvened round, then that sounds good! Thank you!

**Comment by dtatarenkov** [comment]
ok, will be done

**Comment by phoebexy** [comment]
@dtatarenkov any updates?

**Comment by dtatarenkov** [comment]
fixed in dev
