### ISSUE TITLE
Survey Data Displays Incorrectly on Frontend UI

### ISSUE THREAD

**Issue by xehu** [StanfordHCI/bang#482]
We have discovered a critical bug where the survey results, as displayed on the frontend, are not correct. **Instead of displaying the actual survey result, they display the same survey result for every single user.**

In this JSON Viewer screenshot, you can see that, in Round 2, users had different responses to the MidSurvey:
<img width="556" alt="Screen Shot 2020-02-05 at 11 35 22 PM" src="https://user-images.githubusercontent.com/28793641/73917637-a9c6b680-4874-11ea-8078-4af353f8db45.png">

However, these screenshots show that **the survey results for the same round all shows as '3', for every single user.**
<img width="368" alt="Screen Shot 2020-02-05 at 11 37 07 PM" src="https://user-images.githubusercontent.com/28793641/73917707-ce229300-4874-11ea-9c3a-bde35845ae9a.png">
<img width="363" alt="Screen Shot 2020-02-05 at 11 37 14 PM" src="https://user-images.githubusercontent.com/28793641/73917708-cf53c000-4874-11ea-9c55-e2499a5d0d46.png">
<img width="258" alt="Screen Shot 2020-02-05 at 11 37 00 PM" src="https://user-images.githubusercontent.com/28793641/73917709-cfec5680-4874-11ea-97c8-6474ad1e3c9c.png">
<img width="339" alt="Screen Shot 2020-02-05 at 11 37 20 PM" src="https://user-images.githubusercontent.com/28793641/73917711-cfec5680-4874-11ea-934a-31cb07a75dd3.png">

It seems like the survey results in the backend are not showing up on the frontend.

**Comment by xehu** [comment]
Tagging @phoebexy because this issue also impacts her.

**Comment by dtatarenkov** [comment]
in dev

**Comment by xehu** [comment]
This looks great - we can push this to prod
