### ISSUE TITLE
[HIGH PRIORITY] Add user ID to JSON when survey questions include: user_own_name, team_partner_1, team_partner_2, team_partner_3

### ISSUE THREAD

**Issue by phoebexy** [StanfordHCI/bang#483]
For survey questions that use the following tags: user_own_name, team_partner_1, team_partner_2, team_partner_3, we need to add a field in the result array to include the ID of the user whose pseudonym is displayed in the question.

In other words:

For each question result_array, add a field: "id" that logs the MTurk user ID which is referenced in the question is if the question uses: user_own_name, team_partner_1, team_partner_2, team_partner_3.

This is currently the data we get:

`"questions": [
                  {
                    "result_array": [
                    ],
                    "_id": "5e33524cc73b496680fad1eb",
                    "result": ""
                  },
                  {
                    "result_array": [
                    ],
                    "_id": "5e33524cc73b496680fad1ea",
                    "result": "6"
                  },
                  {
                    "result_array": [
                    ],
                    "_id": "5e33524cc73b496680fad1e9",
                    "result": "1"
                  },
                  {
                    "result_array": [
                    ],
                    "_id": "5e33524cc73b496680fad1e8",
                    "result": "6"
                  },
                  {
                    "result_array": [
                    ],
                    "_id": "5e33524cc73b496680fad1e7",
                    "result": "6"
                  },
                  {
                    "result_array": [
                    ],
                    "_id": "5e33524cc73b496680fad1e6",
                    "result": "0"
                  },
                 ...
`

This is what we want:

`"questions": [
                  {
                    "result_array": [
                    ],
                    "_id": "5e33524cc73b496680fad1eb",
                    "result": ""
                  },
                  {
                    "result_array": [
                    ],
                    "_id": "5e33524cc73b496680fad1ea",
                    "result": "6"
                    "user":"5d482eab21c9be351f76425a"
                  },
                  {
                    "result_array": [
                    ],
                    "_id": "5e33524cc73b496680fad1e9",
                    "result": "1"
                    "user":"5d482eab21c9be351f76421b"
                  },
                  {
                    "result_array": [
                    ],
                    "_id": "5e33524cc73b496680fad1e8",
                    "result": "6"
                    "user":"5d482eab21c9be351f76421e"
                  },
                  {
                    "result_array": [
                    ],
                    "_id": "5e33524cc73b496680fad1e7",
                    "result": "6"
                    "user":"5d482eab21c9be351f76421c"
                  },
                 ...
`

**Comment by dtatarenkov** [comment]
in dev
