### ISSUE TITLE
Make it possible to turn off reconvening for single-round tasks.

### ISSUE THREAD

**Issue by xehu** [StanfordHCI/bang#484]
By default, when I do a single-team round, at least one of the rounds reconvenes, and you see the old chat logs. This is related to the original design of single-team rounds by Irena, and described in #428.

As a result, you will see tasks from previous rounds in a later round, like this example (where a task from round 2 is seen in round 4):
<img width="1153" alt="Screen Shot 2020-02-09 at 2 16 50 PM" src="https://user-images.githubusercontent.com/28793641/74113096-e5080480-4b56-11ea-8f22-c392ccecef2d.png">

Currently, the "don't reconvene" button makes it such that **you don't reconvene worst, but one round is still reconvened.**

This ticket requests another toggle: **please make it possible to not reconvene ANY rounds AT ALL.**

The expectation is that, if there are 4 rounds, all 4 rounds have different nicknames.

**Comment by xehu** [comment]
This is high-priority for me personally because it blocks me from being able to run single-team rounds; I need to _not_ have the reconvene feature.

**Comment by dtatarenkov** [comment]
in dev

**Comment by xehu** [comment]
Thanks for this - just tested, it works! :) we can move to prod
