### ISSUE TITLE
Poll Response Data is Not Being Stored

### ISSUE THREAD

**Issue by xehu** [StanfordHCI/bang#486]
The poll response data is not being stored. I ran a test that included a poll with a **text** input, and I typed recognizable phrases like "Emily" or "Mark" into the poll. 

When I search for "Emily," **it does not show up**:
<img width="461" alt="Screen Shot 2020-02-11 at 11 32 39 PM" src="https://user-images.githubusercontent.com/28793641/74312591-d7a17480-4d26-11ea-91b0-0d217f34dd87.png">

Furthermore, there is no indication of the text responses being stored anywhere. In the JSON object viewer, I see only 'pollInd: 0':

<img width="173" alt="Screen Shot 2020-02-11 at 11 12 05 PM" src="https://user-images.githubusercontent.com/28793641/74312720-0a4b6d00-4d27-11ea-93c5-5face55c4a7a.png">

**This seems to be true regardless of what type of input I use. I also tried the 'option' input, and I chose option 4:**
<img width="239" alt="Screen Shot 2020-02-11 at 11 36 50 PM" src="https://user-images.githubusercontent.com/28793641/74313136-f5bba480-4d27-11ea-83a5-1178edbc46c5.png">

However, **in the JSON, pollInd: 0 as usual.** The true answer is not recorded.
<img width="362" alt="Screen Shot 2020-02-11 at 11 39 48 PM" src="https://user-images.githubusercontent.com/28793641/74313168-053aed80-4d28-11ea-9e0e-1e567b7fddbe.png">

This bug is important because it blocks me from being able to use the poll feature---it is not useful if the data cannot be recorded.

**Comment by dtatarenkov** [comment]
poll data was being stored, but wasn't displaying, no should work. in dev

**Comment by xehu** [comment]
confirming that it works! thanks!
