### ISSUE TITLE
Polls no longer correctly check for being 'in agreement' or display live results

### ISSUE THREAD

**Issue by xehu** [StanfordHCI/bang#488]
First of all, thank you for implementing the more complicated version of polls! :) I love the 'expand' and 'collapse' feature, and the ability to have more complex questions. However, the new version of polls unfortunately has lost the 2 pieces of key functionality in the polls design:

1. Participants need to be able to **see what other participants are voting for**---i.e., track results in real time. The previous version had the ability to see the percentages. The design would look something like this Twitter poll:

<img width="381" alt="Screen Shot 2020-02-11 at 11 58 50 PM" src="https://user-images.githubusercontent.com/28793641/74314599-87c4ac80-4d2a-11ea-8fb7-e56738b8e3ef.png">

2. Participants need to be able to **change their vote as they view which ones are popular, and keep changing until the final verdict has full agreement (or meets the threshold).** 

Currently, after you vote once, the screen just says "Thank you!" with no feedback:
<img width="421" alt="Screen Shot 2020-02-11 at 11 50 09 PM" src="https://user-images.githubusercontent.com/28793641/74314675-b2166a00-4d2a-11ea-92a6-f78e0285f70f.png">

Additionally, even though I did this test and voted "1" for every single user, the "not everyone is in agreement" warning remained, which indicates that it seems like we are no longer correctly tracking live votes:

<img width="414" alt="Screen Shot 2020-02-11 at 11 50 03 PM" src="https://user-images.githubusercontent.com/28793641/74314718-cbb7b180-4d2a-11ea-9d40-6b69e1135849.png">

The priority here is also quite high, because the core value-add of polls is the ability to do these two features.

-----
## How to calculate the threshold (edge cases)
One additional point: I realize that the adding of complex features like "checkboxes" and "text" makes it hard to calculate whether we meet the threshold or not.

I would like the solution for this to be that **thresholds / the warning message about not meeting the threshold are only displayed when we have a single-option poll.**

If there are multiple single-option questions, **please add a checkbox that says, "is primary," so that the experimenter can choose which single-option question is the "primary" one.** Then, the live results and meeting the threshold should be calculated with respect to the primary poll option.

**Comment by dtatarenkov** [comment]
hi, I think there is some misunderstanding with this issue, the 'primary' question feature is already implemented
![image](https://user-images.githubusercontent.com/56363169/74506798-a1711a00-4f0b-11ea-9e0a-aafaf7c85d5b.png)
The error logic works like this: if the primary question doesn't meet the threshold condition, we display the error message. There was a small problem with the polls, that don't have a primary question, the error was showing anyways, that is fixed now. 

So, right now we have the following logic: 
1. If there is a primary question, we display/don't display the error message according to the threshold
2. if there is no primary question, we don't display errors at all
3. after submitting the form with all the non-primary questions, we display "Thank you" message

Is this OK? @xehu

**Comment by xehu** [comment]
Your 3 points of logic make sense to me! When I get the chance, I will test them later this weekend. I didn't realize that was how this feature worked; thank you for explaining.

What about the ability to **change your vote based on what others are voting for**? If something is 'primary,' you can change your vote, correct?

**Comment by dtatarenkov** [comment]
that is true @xehu, he can tap on other options in primary question and that will change his answer

**Comment by xehu** [comment]
tested this + fixed a small bug just now, but otherwise this is ready to go
