### ISSUE TITLE
Cases are broken + request to handle long cases

### ISSUE THREAD

**Issue by xehu** [StanfordHCI/bang#490]
I defined these cases:

<img width="987" alt="Screen Shot 2020-02-12 at 12 33 36 AM" src="https://user-images.githubusercontent.com/28793641/74318040-513e6000-4d31-11ea-8f38-a79e6f39d9d7.png">

But **they did not show up during the round.** Are the cases broken?

_For reference: I was testing locally, on the `newarch` branch._

---------------
## What I was testing for:
1. I wanted to make sure **reading periods show up.** That is, a unique reading period comes up for each case.

2. I wanted to make sure that **cases get automatically pinned to the top of the chat.** One edge case that I want to consider is when the cases are too long - I don't want them to over-run the entire chat. 

If the case is longer than 2 lines long, I would like to suggest an **expand/collapse feature,** similar to how the new polls can be expanded and collapsed.

Here's a sketch of how that would work:
![new doc 2020-02-12 00 54 58_1](https://user-images.githubusercontent.com/28793641/74318577-610a7400-4d32-11ea-9040-3ea8e8891865.jpg)

**Comment by dtatarenkov** [comment]
hey, @xehu, after some testing I couldn't reconvene this bug, reading periods do appear on my machine, perhaps you do not turn the dynamic team switch on on addBatch page? It should be turned on because of the roundPairs logic. The case pin logic works bad with long cases, that will be fixed

**Comment by dtatarenkov** [comment]
in dev
