### ISSUE TITLE
Round sometimes skips a survey and adds the time to the next round

### ISSUE THREAD

**Issue by xehu** [StanfordHCI/bang#492]
There is a glitch sometimes, where the round skips a survey and adds the time meant for the survey to the chat time instead.

For example, the round was supposed to be 1 minute. This particular users got more than 1 minute:
<img width="1076" alt="surveyskipped-roundtoolong" src="https://user-images.githubusercontent.com/28793641/75121287-798a6080-5647-11ea-9265-7dec00892259.png">

Meanwhile, other users saw this survey:
<img width="1076" alt="survey-actual" src="https://user-images.githubusercontent.com/28793641/75121289-7ee7ab00-5647-11ea-83d2-d027f20209a1.png">

**Comment by dtatarenkov** [comment]
fixed
