### ISSUE TITLE
Pairs contain an individual + a group, but should contain 2 individual + 2 group

### ISSUE THREAD

**Issue by xehu** [StanfordHCI/bang#502]
This is my fault when initially specifying the design. I have a better understanding of how we want the experiment to work now, and realized that the way we initially specified the functionality no longer matches up with how this should work.

If we have case pairs {**A, A'**} and {**B, B'**},  and we assign case **A** to a group, then **A'** needs to be assigned to a group as well, so that we can measure the consistency within matched cases. 

Critically, the way the functionality was specified does the exact opposite:

**[My initial specification]**
_We will divide all of the rounds into pairs. Within a pair of rounds, one will have a n-person team (in practice, n=6) and one round will have 6 one-person teams._

_Two rounds that are paired together will have another property: they will have different versions of the same case. (More on this in a different issue)._

Yikes!! This means a team is getting case A but an individual is getting A', making it impossible to make the comparisons we need. This is a major issue for the experiment. I (@xehu) will be personally working on this---I am just making this Issue to document what I'm working on.

**Comment by markwhiting** [comment]
Thanks. Let me know if you want to talk through it at all.

**Comment by xehu** [comment]
latest PR has been pushed in and fixes this issue!
