### ISSUE TITLE
Occasionally users are kicked out for being inactive when they are, in fact, active

### ISSUE THREAD

**Issue by xehu** [StanfordHCI/bang#518]
I have received 4-5 emails like this one:

_how was i not active??? i wrote you a whole damn paragraph! i explained my reasoning thoroughly like you wanted and within the time limits... i have no clue how this happened! but im upset_

_I just got this message:THIS TASK REQUIRES WORKERS TO BE ACTIVE IN EVERY ROUND TO WORK. BECAUSE YOU WERE NOT ACTIVE IN THE LAST ROUND YOUR SESSION HAS BEEN STOPPED. I was fully active and had just submitted my 1st survey with 5 seconds remaining on the clock and got this.  What did I do wrong???_

Users report that they are removed from the study for being inactive even after they demonstrate being active. This seems to be a rare issue that affects 2-3 users every 10-15 batches.

**Comment by markwhiting** [comment]
Thanks @xehu  
If you get a chance, could you try to track down a relevant log snippet and put it here.

**Comment by xehu** [comment]
After tracking down this issue and communicating with all workers who report this, I've determined that this is a UI issue, which is now consolidated into #526.
