### ISSUE TITLE
Pressing the "Notify Users with Join Link" button does not work

### ISSUE THREAD

**Issue by xehu** [StanfordHCI/bang#522]
When you press "notify users with join link" on the notify page, you get 'done' immediately -- then, when you check the front-end logs, you see that 0 workers were notified.

This is an issue, since I try to email (and notify) far more than the default 200. Otherwise, we won't get enough batches to roll over.

**Comment by markwhiting** [comment]
This should be `isTest = false`. Right now its sending test users notifications. I messed this up. Sorry!

https://github.com/StanfordHCI/bang/blob/199665663f751e72e6c10a92d05db6ead49bb696/server/controllers/admin.ts#L627
