### ISSUE TITLE
Server sometimes fails to pull and rebuild prod correctly

### ISSUE THREAD

**Issue by markwhiting** [StanfordHCI/bang#524]
This has lead to some updates (especially `.ts`) not getting executed. Right now the best fix is to manually pull on `prod`.

**Comment by xehu** [comment]
@markwhiting just as a follow-up: how do you manually pull on prod? I'm still seeing that the server isn't reflecting the updated .ts file.

**Comment by markwhiting** [comment]
I think this is a non-issue and was caused by us committing a fix in the wrong place.
